name: Deploy Resume to Pages
on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Web Folder
        run: mkdir -p ./public

      - name: Render PDF via Pandoc
        uses: docker://pandoc/latex:latest
        with:
          args: >-
            --template eisvogel.tex
            -o ./public/resume.pdf
            resume.md

      - name: Prepare Assets
        run: cp index.html ./public/

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4